# https://www.appveyor.com/docs/appveyor-yml/

# test 9;

#---------------------------------#
#      general configuration      #
#---------------------------------#

# branches to build
branches:
  # blacklist
  except:
    - gh-pages

# Maximum number of concurrent jobs for the project
max_jobs: 1

# environment variables
# environment:
#   my_var1: value1
#   my_var2: value2
#   # this is how to set encrypted variable. Go to "Encrypt data" page in account menu to encrypt data.
#   my_secure_var1:
#     secure: FW3tJ3fMncxvs58/ifSP7w==

environment:
  access_token:
    # Github access token
    secure: U0VBux6UVwlrFl3AnZrVValeccfzslMkPz4Yz5ukyp4GzLpWJuYT2si951UuQiZw

# scripts that run after cloning repository
install:
- cmd: >-
    choco install gitversion.portable --pre

    npm install

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
- cmd: >-
    gitversion /output BuildServer

    gitversion /output json

build_script:
- cmd: npm run build:prod

# to disable automatic builds
# build: off

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
- cmd: >-
    npm run lint

    npm test

# to disable automatic tests
# test: off

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# deploy:

  # Deploy to GitHub Releases
  # - provider: GitHub
  #   artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
  #   draft: false
  #   prerelease: false
  #   on:
  #     branch: master                # release from master branch only
  #     appveyor_repo_tag: true       # deploy on tag push only

deploy_script:
- ps: |
    Write-Host $Env:APPVEYOR_REPO_TAG
    Write-Host $Env:APPVEYOR_REPO_BRANCH
    Write-Host $Env:GitVersion_FullSemVer
    if (($Env:APPVEYOR_REPO_TAG -eq "true") -and ($Env:GitVersion_BranchName -eq "master")) {
      git add --ignore-removal dist
      git commit -m "GitHub release"
      git subtree push --prefix dist origin gh-pages
    } elseif ($Env:APPVEYOR_REPO_BRANCH -eq "master") {
      $host.SetShouldExit(1)
      Write-Host "Skipping deploy, master does not have a tag."
    } else {
      Write-Host "Branch not master, skipping deploy."
    }

# to disable deployment
# deploy: off
