# https://www.appveyor.com/docs/appveyor-yml/

#---------------------------------#
#      general configuration      #
#---------------------------------#

# branches to build
branches:
  # blacklist
  except:
    - gh-pages

# Maximum number of concurrent jobs for the project
max_jobs: 1

# environment variables
# environment:
#   my_var1: value1
#   my_var2: value2
#   # this is how to set encrypted variable. Go to "Encrypt data" page in account menu to encrypt data.
#   my_secure_var1:
#     secure: FW3tJ3fMncxvs58/ifSP7w==

# scripts that run after cloning repository
install:
- cmd: npm install

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
- cmd: npm run build:prod

# to disable automatic builds
# build: off

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
- cmd: >-
    npm run lint

    npm test

# to disable automatic tests
# test: off

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# deploy:

  # Deploy to GitHub Releases
  # - provider: GitHub
  #   artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
  #   draft: false
  #   prerelease: false
  #   on:
  #     branch: master                # release from master branch only
  #     appveyor_repo_tag: true       # deploy on tag push only

-
  branches:
    only:
      - master

  deploy_script:
  - ps: |
      if ($Env:APPVEYOR_REPO_TAG -eq "true") {
        git add --ignore-removal dist
        git commit -m "GitHub release"
        git subtree push --prefix dist origin gh-pages
      } else {
        Write-Host "Skipping deploy, master does not have a tag."
        $LastExitCode = 1
      }

# to disable deployment
# deploy: off
