# https://www.appveyor.com/docs/appveyor-yml/

#---------------------------------#
#      general configuration      #
#---------------------------------#

branches:
  except:
    - gh-pages

max_jobs: 1

environment:
  # Github
  access_token:
    secure: IGs25EMrhe0au+uVDbOck6akDzC9ykvJeR0zJjhrT6idNuYOr/JpyGdefQxSlWXk
  github_email:
    secure: U3oByHGtWDiIy9psThpxwg==

# cache:
#   - node_modules

install:
- cmd: >-
    choco install gitversion.portable --pre

    npm install

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
- cmd: gitversion /output BuildServer

build_script:
- cmd: npm run build:prod

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# test_script:
- cmd: >-
    npm run lint

    npm test

test: off

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

before_deploy:
- ps: ./deploy.ps1

deploy:

  # Deploy to GitHub Releases
  - provider: GitHub
    auth_token:
      secure: IGs25EMrhe0au+uVDbOck6akDzC9ykvJeR0zJjhrT6idNuYOr/JpyGdefQxSlWXk
    release: DesignGuide v$(GitVersion_SemVer)
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: $(changelog)
    artifact: /PayEx.DesignGuide.*\.zip/
    draft: true
    prerelease: true
    on:
      appveyor_repo_tag: true

#---------------------------------#
#         notifications           #
#---------------------------------#

# notifications:

  # # Slack
  # - provider: Slack
  #   incoming_webhook: http://incoming-webhook-url

  # # ...or using auth token

  # - provider: Slack
  #   auth_token:
  #     secure: kBl9BlxvRMr9liHmnBs14A==
  #   channel: development
  #   template: "{message}, {commitId}, ..."
