# https://www.appveyor.com/docs/appveyor-yml/

#---------------------------------#
#      general configuration      #
#---------------------------------#

# branches to build
branches:
  # blacklist
  except:
    - gh-pages

# Maximum number of concurrent jobs for the project
max_jobs: 1

environment:
  # Github
  access_token:
    secure: IGs25EMrhe0au+uVDbOck6akDzC9ykvJeR0zJjhrT6idNuYOr/JpyGdefQxSlWXk
  github_email:
    secure: U3oByHGtWDiIy9psThpxwg==

# scripts that run after cloning repository
install:
- cmd: >-
    choco install gitversion.portable --pre

    npm install

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
- cmd: >-
    gitversion /output BuildServer

    gitversion /output json

build_script:
- cmd: npm run build:prod

# to disable automatic builds
# build: off

#---------------------------------#
#       tests configuration       #
#---------------------------------#

## test_script:
# - cmd: >-
#     npm run lint

#     npm test

# to disable automatic tests
test: off

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# deploy:

  # Deploy to GitHub Releases
  # - provider: GitHub
  #   artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
  #   draft: false
  #   prerelease: false
  #   on:
  #     branch: master                # release from master branch only
  #     appveyor_repo_tag: true       # deploy on tag push only

deploy_script:
- ps: ./deploy.ps1

# to disable deployment
# deploy: off
